version: '3.8'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    restart: always
    hostname: 'jenkins'
    privileged: true
    user: root
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '2376:8080'
      - '2377:50000'
    volumes:
      - '$GENKINS_HOME/jenkins-data:/var/jenkins_home'