---
# Add CNI
- name: Copy CNI tarball to target server
  copy:
    src: "../roles/kubelet/release/x86_64/cni/cni-plugins-linux-amd64-v1.5.1.tgz"
    dest: "/tmp"

- name: Ensure /opt/cni/bin directory exists
  file:
    path: "/opt/cni/bin"
    state: directory
    mode: "0755"

- name: Extract CNI tarball to /opt/cni/bin
  ansible.builtin.unarchive:
    src: "/tmp/cni-plugins-linux-amd64-v1.5.1.tgz"
    dest: "/opt/cni/bin"
    remote_src: yes
