---
# Add CNI
- name: Copy CNI tarball to target server
  copy:
    src: "../roles/CNI/release/{{ arch }}/{{ version }}/{{ pkg }}"
    dest: "/tmp"

- name: Ensure /opt/cni/bin directory exists
  file:
    path: "/opt/cni/bin"
    state: directory
    mode: "0755"

- name: Extract CNI tarball to /opt/cni/bin
  ansible.builtin.unarchive:
    src: "/tmp/{{ pkg }}"
    dest: "/opt/cni/bin"
    remote_src: yes
