kubernetes:
  kubectl:
    x86_64:
      v1.31.0:
        - name: "kubectl"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl"
    arrach64:
      v1.31.0:
        - name: "kubectl"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/arm64/kubectl"
  
  kubeadm:
    x86_64:
      v1.31.0:
        - name: "kubeadm"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubeadm"
    arrach64:
      v1.31.0:
        - name: "kubeadm"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/arm64/kubeadm"

  kubelet:
    x86_64:
      v1.31.0:
        - name: "kubelet"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubelet"
    arrach64:
      v1.31.0:
        - name: "kubelet"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/arm64/kubelet"

