kubernetes:
  kubectl:
    x86_64:
      v1.31.0:
        - name: "kubectl"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl"
    arrach64:
      v1.31.0:
        - name: "kubectl"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/arm64/kubectl"
  
  kubeadm:
    x86_64:
      v1.31.0:
        - name: "kubeadm"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubeadm"
    arrach64:
      v1.31.0:
        - name: "kubeadm"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/arm64/kubeadm"

  kubelet:
    x86_64:
      v1.31.0:
        - name: "kubelet"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubelet"
    arrach64:
      v1.31.0:
        - name: "kubelet"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/arm64/kubelet"

  helm:
    x86_64:
      v3.15.4:
        - name: "helm-v3.15.4-linux-amd64.tar.gz"
          source: "https://get.helm.sh/helm-v3.15.4-linux-amd64.tar.gz"
    arrach64:
      v3.15.4:
        - name: "helm-v3.15.4-linux-arm64.tar.gz"
          source: "https://get.helm.sh/helm-v3.15.4-linux-arm64.tar.gz"

  nerdctl:
    x86_64:
      1.7.6:
        - name: "nerdctl-full-1.7.6-linux-amd64.tar.gz"
          source: "https://github.com/containerd/nerdctl/releases/download/v1.7.6/nerdctl-full-1.7.6-linux-amd64.tar.gz"
    arrach64:
      1.7.6:
        - name: "nerdctl-full-1.7.6-linux-arm64.tar.gz"
          source: "https://github.com/containerd/nerdctl/releases/download/v1.7.6/nerdctl-full-1.7.6-linux-arm64.tar.gz"

  docker:
    x86_64:
      27.1.2:
        - name: "docker-27.1.2.tgz"
          source: "https://download.docker.com/linux/static/stable/x86_64/docker-27.1.2.tgz"
        - name: "docker-rootless-extras-27.1.2.tgz"
          source: "https://download.docker.com/linux/static/stable/x86_64/docker-rootless-extras-27.1.2.tgz"
    arrach64:
      27.1.2:
        - name: "docker-27.1.2.tgz"
          source: "https://download.docker.com/linux/static/stable/aarch64/docker-27.1.2.tgz"
        - name: "docker-rootless-extras-27.1.2.tgz"
          source: "https://download.docker.com/linux/static/stable/aarch64/docker-rootless-extras-27.1.2.tgz"

  docker-compose:
    x86_64:
      v2.29.2:
        - name: "docker-compose-linux-x86_64"
          source: "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64"
    arrach64:
      v2.29.2:
        - name: "docker-compose-linux-aarch64"
          source: "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-aarch64"

  docker-compose:
    x86_64:
      v2.29.2:
        - name: "docker-compose-linux-x86_64"
          source: "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64"
    arrach64:
      v2.29.2:
        - name: "docker-compose-linux-aarch64"
          source: "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-aarch64"

  docker-buildx:
    x86_64:
      v0.16.2:
        - name: "buildx-v0.16.2.linux-amd64"
          source: "https://github.com/docker/buildx/releases/download/v0.16.2/buildx-v0.16.2.linux-amd64"
    arrach64:
      v0.16.2:
        - name: "buildx-v0.16.2.linux-arm64"
          source: "https://github.com/docker/buildx/releases/download/v0.16.2/buildx-v0.16.2.linux-arm64"