kubernetes:
  kubectl:
    x86_64:
      v1.31.0:
        - name: "kubectl"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl"
    arrach64:
      v1.31.0:
        - name: "kubectl"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/arm64/kubectl"

