kubernetes:
  kubectl:
    x86_64:
      v1.31.0:
        - name: "kubectl"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl"
    arrach64:
      v1.31.0:
        - name: "kubectl"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/arm64/kubectl"

  kubeadm:
    x86_64:
      v1.31.0:
        - name: "kubeadm"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubeadm"
    arrach64:
      v1.31.0:
        - name: "kubeadm"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/arm64/kubeadm"

  kubelet:
    x86_64:
      v1.31.0:
        - name: "kubelet"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubelet"
    arrach64:
      v1.31.0:
        - name: "kubelet"
          source: "https://dl.k8s.io/release/v1.31.0/bin/linux/arm64/kubelet"

  helm:
    x86_64:
      v3.15.4:
        - name: "helm-v3.15.4-linux-amd64.tar.gz"
          source: "https://get.helm.sh/helm-v3.15.4-linux-amd64.tar.gz"
    arrach64:
      v3.15.4:
        - name: "helm-v3.15.4-linux-arm64.tar.gz"
          source: "https://get.helm.sh/helm-v3.15.4-linux-arm64.tar.gz"

  nerdctl:
    x86_64:
      1.7.6:
        - name: "nerdctl-full-1.7.6-linux-amd64.tar.gz"
          source: "https://github.com/containerd/nerdctl/releases/download/v1.7.6/nerdctl-full-1.7.6-linux-amd64.tar.gz"
    arrach64:
      1.7.6:
        - name: "nerdctl-full-1.7.6-linux-arm64.tar.gz"
          source: "https://github.com/containerd/nerdctl/releases/download/v1.7.6/nerdctl-full-1.7.6-linux-arm64.tar.gz"
  CNI:
    x86_64:
      v1.5.1:
        - name: "cni-plugins-linux-amd64-v1.5.1.tgz"
          source: "https://github.com/containernetworking/plugins/releases/download/v1.5.1/cni-plugins-linux-amd64-v1.5.1.tgz"
    arrach64:
      v1.5.1:
        - name: "cni-plugins-linux-arm64-v1.5.1.tgz"
          source: "https://github.com/containernetworking/plugins/releases/download/v1.5.1/cni-plugins-linux-arm64-v1.5.1.tgz"

  CRI:
    x86_64:
      v1.31.0:
        - name: "crictl-v1.31.0-linux-amd64.tar.gz"
          source: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.31.0/crictl-v1.31.0-linux-amd64.tar.gz"
    arrach64:
      v1.31.0:
        - name: "crictl-v1.31.0-linux-arm64.tar.gz"
          source: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.31.0/crictl-v1.31.0-linux-arm64.tar.gz"

docker:
  docker:
    x86_64:
      27.1.2:
        - name: "docker-27.1.2.tgz"
          source: "https://download.docker.com/linux/static/stable/x86_64/docker-27.1.2.tgz"
        - name: "docker-rootless-extras-27.1.2.tgz"
          source: "https://download.docker.com/linux/static/stable/x86_64/docker-rootless-extras-27.1.2.tgz"
    arrach64:
      27.1.2:
        - name: "docker-27.1.2.tgz"
          source: "https://download.docker.com/linux/static/stable/aarch64/docker-27.1.2.tgz"
        - name: "docker-rootless-extras-27.1.2.tgz"
          source: "https://download.docker.com/linux/static/stable/aarch64/docker-rootless-extras-27.1.2.tgz"

  docker-compose:
    x86_64:
      v2.29.2:
        - name: "docker-compose-linux-x86_64"
          source: "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64"
    arrach64:
      v2.29.2:
        - name: "docker-compose-linux-aarch64"
          source: "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-aarch64"

  docker-buildx:
    x86_64:
      v0.16.2:
        - name: "buildx-v0.16.2.linux-amd64"
          source: "https://github.com/docker/buildx/releases/download/v0.16.2/buildx-v0.16.2.linux-amd64"
    arrach64:
      v0.16.2:
        - name: "buildx-v0.16.2.linux-arm64"
          source: "https://github.com/docker/buildx/releases/download/v0.16.2/buildx-v0.16.2.linux-arm64"

linux:
  conntrack:
    x86_64:
      1.4.7:
        - name: "conntrack_1.4.7-1+b2_amd64.deb"
          source: "http://ftp.cn.debian.org/debian/pool/main/c/conntrack-tools/conntrack_1.4.7-1+b2_amd64.deb"
        - name: "conntrack-tools-1.4.7-2.el9.x86_64.rpm"
          source: "https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/conntrack-tools-1.4.7-2.el9.x86_64.rpm"
        - name: "libnetfilter_cthelper-1.0.0-22.el9.x86_64.rpm"
          source: "https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/libnetfilter_cthelper-1.0.0-22.el9.x86_64.rpm"
        - name: "libnetfilter_cttimeout-1.0.0-19.el9.x86_64.rpm"
          source: "https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/libnetfilter_cttimeout-1.0.0-19.el9.x86_64.rpm"
        - name: "libnetfilter_queue-1.0.5-1.el9.x86_64.rpm"
          source: "https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/libnetfilter_queue-1.0.5-1.el9.x86_64.rpm"
    arrach64:
      1.4.7:
        - name: "conntrack_1.4.7-1+b2_arm64.deb"
          source: "http://ftp.cn.debian.org/debian/pool/main/c/conntrack-tools/conntrack_1.4.7-1+b2_arm64.deb"
        - name: "conntrack-tools-1.4.7-2.el9.aarch64.rpm"
          source: "https://rpmfind.net/linux/centos-stream/9-stream/AppStream/aarch64/os/Packages/conntrack-tools-1.4.7-2.el9.aarch64.rpm"
        - name: "libnetfilter_cthelper-1.0.0-22.el9.aarch64.rpm"
          source: "https://rpmfind.net/linux/centos-stream/9-stream/AppStream/aarch64/os/Packages/libnetfilter_cthelper-1.0.0-22.el9.aarch64.rpm"
        - name: "libnetfilter_cttimeout-1.0.0-19.el9.aarch64.rpm"
          source: "https://rpmfind.net/linux/centos-stream/9-stream/AppStream/aarch64/os/Packages/libnetfilter_cttimeout-1.0.0-19.el9.aarch64.rpm"
        - name: "libnetfilter_queue-1.0.5-1.el9.aarch64.rpm"
          source: "https://rpmfind.net/linux/centos-stream/9-stream/AppStream/aarch64/os/Packages/libnetfilter_queue-1.0.5-1.el9.aarch64.rpm"
  socat:
    x86_64:
      1.7.4:
        - name: "socat_1.7.4.4-2_amd64.deb"
          source: "http://ftp.cn.debian.org/debian/pool/main/s/socat/socat_1.7.4.4-2_amd64.deb"
        - name: "socat-1.7.4.1-5.el9_4.2.x86_64.rpm"
          source: "https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/socat-1.7.4.1-5.el9.x86_64.rpm"
    arrach64:
      1.7.4:
        - name: "socat_1.7.4.4-2_arm64.deb"
          source: "http://ftp.cn.debian.org/debian/pool/main/s/socat/socat_1.7.4.4-2_arm64.deb"
        - name: "socat-1.7.4.1-5.el9.aarch64.rpm"
          source: "https://rpmfind.net/linux/centos-stream/9-stream/AppStream/aarch64/os/Packages/socat-1.7.4.1-5.el9.aarch64.rpm"      