---
- name: Ensure the /etc/kubernetes/ directory exists
  file:
    path: /etc/kubernetes/
    state: directory
    mode: "0755"

- name: Copy init conf to target server
  copy:
    src: "../roles/kubeadm/conf/init-control-plane.yml"
    dest: "/etc/kubernetes/"

- name: Enable and start kubelet service
  command: sudo systemctl enable --now kubelet
  become: yes
  changed_when: false
