---
- name: Ensure the /etc/kubernetes/ directory exists
  file:
    path: /etc/kubernetes/
    state: directory
    mode: "0755"

- name: Copy init conf to target server
  copy:
    src: "../roles/kubeadm/conf/init-control-plane.yml"
    dest: "/etc/kubernetes/"

- name: Enable and start kubelet service
  command: sudo systemctl enable --now kubelet
  become: yes
  changed_when: false

- name: Copy 10-kubeadm.conf to /usr/lib/systemd/system/kubelet.service.d
  copy:
    src: "../roles/kubeadm/conf/10-kubeadm.conf"
    dest: "/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf"
    mode: "0644"

# Add main binaries
- name: Copy kubeadm binary to /usr/local/bin
  copy:
    src: "../roles/kubeadm/release/x86_64/v1.31.0/kubeadm"
    dest: "/usr/local/bin/kubeadm"
    mode: "0755"

# Plugin
- name: Ensure the /etc/kubernetes/calico directory exists
  file:
    path: /etc/kubernetes/calico
    state: directory
    mode: "0755"

- name: Copy calico to target server
  copy:
    src: "../roles/kubeadm/conf/calico/v3.28.1/calico.yaml"
    dest: "/etc/kubernetes/calico"

- name: Ensure the /etc/kubernetes/metrics-server directory exists
  file:
    path: /etc/kubernetes/metrics-server
    state: directory
    mode: "0755"

- name: Copy metrics-server components to target server
  copy:
    src: "../roles/kubeadm/conf/metrics-server/v0.7.1/components.yaml"
    dest: "/etc/kubernetes/metrics-server"

- name: Copy metrics-server availability to target server
  copy:
    src: "../roles/kubeadm/conf/metrics-server/v0.7.1/high-availability-1.21+.yaml"
    dest: "/etc/kubernetes/metrics-server"
