---
arch: x86_64
version: 1.17.4

package:
  x86_64:
    1.17.4:
      deb:
        - "libnvidia-container-dev_1.17.4-1_amd64.deb"
        - "libnvidia-container-tools_1.17.4-1_amd64.deb"
        - "libnvidia-container1-dbg_1.17.4-1_amd64.deb"
        - "libnvidia-container1_1.17.4-1_amd64.deb"
        - "nvidia-container-toolkit-base_1.17.4-1_amd64.deb"
        - "nvidia-container-toolkit_1.17.4-1_amd64.deb"
