---
# Add CRI
- name: Copy CRI tarball to target server
  copy:
    src: "../roles/kubelet/release/x86_64/cri/{{ cri_tarball }}"
    dest: "/tmp"

- name: Ensure /usr/local/bin directory exists
  file:
    path: "/usr/local/bin"
    state: directory
    mode: "0755"

- name: Extract CRI tarball to /usr/local/bin
  ansible.builtin.unarchive:
    src: "/tmp/{{ cri_tarball }}"
    dest: "/usr/local/bin"
    remote_src: yes

- name: Copy CRI configuration to /etc
  copy:
    src: "../roles/kubelet/release/x86_64/cri/crictl.yaml"
    dest: "/etc/crictl.yaml"
    mode: "0644"

# Add CNI
- name: Copy CNI tarball to target server
  copy:
    src: "../roles/kubelet/release/x86_64/cni/{{ cni_tarball }}"
    dest: "/tmp"

- name: Ensure /opt/cni/bin directory exists
  file:
    path: "/opt/cni/bin"
    state: directory
    mode: "0755"

- name: Extract CNI tarball to /opt/cni/bin
  ansible.builtin.unarchive:
    src: "/tmp/{{ cni_tarball }}"
    dest: "/opt/cni/bin"
    remote_src: yes

# Remove temporary files
- name: Remove temporary files
  file:
    path: "/tmp/{{ item }}"
    state: absent
  loop:
    - "{{ cri_tarball }}"
    - "{{ cni_tarball }}"

- name: Copy kubelet binary to /usr/local/bin
  copy:
    src: "../roles/kubelet/release/x86_64/main/kubelet"
    dest: "/usr/local/bin/kubelet"
    mode: "0755"

# Add kubelet config
- name: Ensure /usr/lib/systemd/system directory exists
  file:
    path: "/usr/lib/systemd/system"
    state: directory
    mode: "0755"

- name: Copy kubelet.service to /usr/lib/systemd/system
  copy:
    src: "../roles/kubelet/conf/kubelet.service"
    dest: "/usr/lib/systemd/system/kubelet.service"
    mode: "0644"

- name: Ensure /usr/lib/systemd/system/kubelet.service.d directory exists
  file:
    path: "/usr/lib/systemd/system/kubelet.service.d"
    state: directory
    mode: "0755"

# - name: Enable and start kubelet service
#   command: systemctl enable --now kubelet

