- name: Manage kubelet service
  hosts: servers
  become: yes
  tasks:
    - name: Stop kubelet service
      ansible.builtin.systemd:
        name: kubelet
        state: stopped

    - name: Disable kubelet service
      ansible.builtin.systemd:
        name: kubelet
        enabled: no