version: '3'
services:
    oracle:
      #port: 1521
      #sid: xe
      #username: system
      #password: oracle
      container_name: oracle
      image: oracleinanutshell/oracle-xe-11g:latest
      environment:
        - TZ=Asia/Shanghai
        - ORACLE_ALLOW_REMOTE=true
        - ORACLE_ENABLE_XDB=true
      restart: always
      ports:
        - "1521:1521"