---
- name: 检查是否启用了 cgroup v2
  stat:
    path: /sys/fs/cgroup/cgroup.controllers
  register: cgroup_v2_check

- name: 设置 cgroup v2 启用标志
  set_fact:
    cgroup_v2_enabled: "{{ cgroup_v2_check.stat.exists }}"

- name: 读取 cgroup v2 文件内容
  slurp:
    path: /sys/fs/cgroup/cgroup.controllers
  register: cgroup_v2_file_content
  when: cgroup_v2_check.stat.exists

- name: 输出 cgroup v2 文件内容
  debug:
    msg: "cgroup v2 values {{ cgroup_v2_file_content.content | b64decode }}"
  when: cgroup_v2_check.stat.exists

- name: 输出 cgroup v2 状态
  debug:
    msg: "cgroup v2 未启用。"
  when: not cgroup_v2_check.stat.exists
  failed_when: not cgroup_v2_check.stat.exists
