---
- name: Copy kubectl binary to /usr/local/bin
  copy:
    src: "../roles/kubernetes/release/{{ arch }}/main/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: "0755"

- name: Ensure bash_completion directory exists
  file:
    path: "/etc/bash_completion.d"
    state: directory
    mode: "0755"

- name: Enable kubectl bash completion
  shell: "kubectl completion bash | tee /etc/bash_completion.d/kubectl > /dev/null"
  args:
    creates: "/etc/bash_completion.d/kubectl"

- name: Ensure kubectl completion script is readable
  file:
    path: "/etc/bash_completion.d/kubectl"
    mode: "0644"

- name: Ensure /etc/profile.d directory exists
  file:
    path: /etc/profile.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Copy kubectl short cmd to /etc/profile.d
  copy:
    src: ../roles/kubelet/config/kube-short-cmd.sh
    dest: /etc/profile.d/kube-short-cmd.sh
    mode: "0755"
    owner: root
    group: root
