---
- name: Remove compose
  hosts: servers
  become: yes
  tasks:
    - name: Remove compose binaries
      file:
        path: "/usr/local/bin/{{ item }}"
        state: absent
      loop:
        - docker-compose
