---
- name: Remove buildx
  hosts: servers
  become: yes
  tasks:
    - name: Remove buildx binaries
      file:
        path: "/usr/local/bin/{{ item }}"
        state: absent
      loop:
        - docker-buildx
