---
- name: Remove kubectl
  hosts: test
  become: yes
  tasks:
    - name: Remove Kubernetes binaries
      file:
        path: "/usr/local/bin/{{ item }}"
        state: absent
      loop:
        - kubectl
