---
- name: Remove kubectl
  hosts: servers
  become: yes
  tasks:
    - name: Remove Kubernetes binaries
      file:
        path: "/usr/local/bin/{{ item }}"
        state: absent
      loop:
        - kubectl
    - name: Remove Kubernetes conf
      file:
        path: "/etc/bash_completion.d/{{ item }}"
        state: absent
      loop:
        - kubectl
