---
- name: Remove nerdctl
  hosts: all
  become: yes
  tasks:
    - name: Stop containerd service
      systemd:
        name: containerd
        state: stopped

    - name: Stop buildkit service
      systemd:
        name: buildkit
        state: stopped

    - name: Stop stargz-snapshotter service
      systemd:
        name: stargz-snapshotter
        state: stopped

    - name: Remove containerd config
      file:
        path: /etc/containerd/config.toml
        state: absent

    - name: Remove /usr/local/bin/buildctl
      file:
        path: /usr/local/bin/buildctl
        state: absent

    - name: Remove /usr/local/bin/buildg
      file:
        path: /usr/local/bin/buildg
        state: absent

    - name: Remove /usr/local/bin/buildkitd
      file:
        path: /usr/local/bin/buildkitd
        state: absent

    - name: Remove /usr/local/bin/bypass4netns
      file:
        path: /usr/local/bin/bypass4netns
        state: absent

    - name: Remove /usr/local/bin/bypass4netnsd
      file:
        path: /usr/local/bin/bypass4netnsd
        state: absent

    - name: Remove /usr/local/bin/containerd
      file:
        path: /usr/local/bin/containerd
        state: absent

    - name: Remove /usr/local/bin/containerd-fuse-overlayfs-grpc
      file:
        path: /usr/local/bin/containerd-fuse-overlayfs-grpc
        state: absent

    - name: Remove /usr/local/bin/containerd-rootless-setuptool.sh
      file:
        path: /usr/local/bin/containerd-rootless-setuptool.sh
        state: absent

    - name: Remove /usr/local/bin/containerd-rootless.sh
      file:
        path: /usr/local/bin/containerd-rootless.sh
        state: absent

    - name: Remove /usr/local/bin/containerd-shim-runc-v2
      file:
        path: /usr/local/bin/containerd-shim-runc-v2
        state: absent

    - name: Remove /usr/local/bin/containerd-stargz-grpc
      file:
        path: /usr/local/bin/containerd-stargz-grpc
        state: absent

    - name: Remove /usr/local/bin/ctd-decoder
      file:
        path: /usr/local/bin/ctd-decoder
        state: absent

    - name: Remove /usr/local/bin/ctr
      file:
        path: /usr/local/bin/ctr
        state: absent

    - name: Remove /usr/local/bin/ctr-enc
      file:
        path: /usr/local/bin/ctr-enc
        state: absent

    - name: Remove /usr/local/bin/ctr-remote
      file:
        path: /usr/local/bin/ctr-remote
        state: absent

    - name: Remove /usr/local/bin/fuse-overlayfs
      file:
        path: /usr/local/bin/fuse-overlayfs
        state: absent

    - name: Remove /usr/local/bin/ipfs
      file:
        path: /usr/local/bin/ipfs
        state: absent

    - name: Remove /usr/local/bin/nerdctl
      file:
        path: /usr/local/bin/nerdctl
        state: absent

    - name: Remove /usr/local/bin/rootlessctl
      file:
        path: /usr/local/bin/rootlessctl
        state: absent

    - name: Remove /usr/local/bin/rootlesskit
      file:
        path: /usr/local/bin/rootlesskit
        state: absent

    - name: Remove /usr/local/bin/runc
      file:
        path: /usr/local/bin/runc
        state: absent

    - name: Remove /usr/local/bin/slirp4netns
      file:
        path: /usr/local/bin/slirp4netns
        state: absent

    - name: Remove /usr/local/bin/tini
      file:
        path: /usr/local/bin/tini
        state: absent

    - name: Remove /usr/local/lib/systemd/system/buildkit.service
      file:
        path: /usr/local/lib/systemd/system/buildkit.service
        state: absent

    - name: Remove /usr/local/lib/systemd/system/containerd.service
      file:
        path: /usr/local/lib/systemd/system/containerd.service
        state: absent

    - name: Remove /usr/local/lib/systemd/system/stargz-snapshotter.service
      file:
        path: /usr/local/lib/systemd/system/stargz-snapshotter.service
        state: absent

    - name: Remove /usr/local/libexec/cni/bandwidth
      file:
        path: /usr/local/libexec/cni/bandwidth
        state: absent

    - name: Remove /usr/local/libexec/cni/bridge
      file:
        path: /usr/local/libexec/cni/bridge
        state: absent

    - name: Remove /usr/local/libexec/cni/dhcp
      file:
        path: /usr/local/libexec/cni/dhcp
        state: absent

    - name: Remove /usr/local/libexec/cni/dummy
      file:
        path: /usr/local/libexec/cni/dummy
        state: absent

    - name: Remove /usr/local/libexec/cni/firewall
      file:
        path: /usr/local/libexec/cni/firewall
        state: absent

    - name: Remove /usr/local/libexec/cni/host-device
      file:
        path: /usr/local/libexec/cni/host-device
        state: absent

    - name: Remove /usr/local/libexec/cni/host-local
      file:
        path: /usr/local/libexec/cni/host-local
        state: absent

    - name: Remove /usr/local/libexec/cni/ipvlan
      file:
        path: /usr/local/libexec/cni/ipvlan
        state: absent

    - name: Remove /usr/local/libexec/cni/loopback
      file:
        path: /usr/local/libexec/cni/loopback
        state: absent

    - name: Remove /usr/local/libexec/cni/macvlan
      file:
        path: /usr/local/libexec/cni/macvlan
        state: absent

    - name: Remove /usr/local/libexec/cni/portmap
      file:
        path: /usr/local/libexec/cni/portmap
        state: absent

    - name: Remove /usr/local/libexec/cni/ptp
      file:
        path: /usr/local/libexec/cni/ptp
        state: absent

    - name: Remove /usr/local/libexec/cni/sbr
      file:
        path: /usr/local/libexec/cni/sbr
        state: absent

    - name: Remove /usr/local/libexec/cni/static
      file:
        path: /usr/local/libexec/cni/static
        state: absent

    - name: Remove /usr/local/libexec/cni/tap
      file:
        path: /usr/local/libexec/cni/tap
        state: absent

    - name: Remove /usr/local/libexec/cni/tuning
      file:
        path: /usr/local/libexec/cni/tuning
        state: absent

    - name: Remove /usr/local/libexec/cni/vlan
      file:
        path: /usr/local/libexec/cni/vlan
        state: absent

    - name: Remove /usr/local/libexec/cni/vrf
      file:
        path: /usr/local/libexec/cni/vrf
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/builder-debug.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/builder-debug.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/build.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/build.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/cni.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/cni.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/command-reference.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/command-reference.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/compose.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/compose.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/config.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/config.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/cosign.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/cosign.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/cvmfs.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/cvmfs.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/dir.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/dir.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/experimental.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/experimental.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/faq.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/faq.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/freebsd.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/freebsd.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/gpu.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/gpu.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/ipfs.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/ipfs.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/multi-platform.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/multi-platform.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/notation.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/notation.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/nydus.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/nydus.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/ocicrypt.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/ocicrypt.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/overlaybd.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/overlaybd.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/registry.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/registry.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/rootless.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/rootless.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/soci.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/soci.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/docs/stargz.md
      file:
        path: /usr/local/share/doc/nerdctl/docs/stargz.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl/README.md
      file:
        path: /usr/local/share/doc/nerdctl/README.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl-full/README.md
      file:
        path: /usr/local/share/doc/nerdctl-full/README.md
        state: absent

    - name: Remove /usr/local/share/doc/nerdctl-full/SHA256SUMS
      file:
        path: /usr/local/share/doc/nerdctl-full/SHA256SUMS
        state: absent

    # After run file
    - name: Forcefully remove /var/lib/containerd and its contents
      command: rm -rf /var/lib/containerd
      ignore_errors: yes

    - name: Forcefully remove /var/lib/buildkit and its contents
      command: rm -rf /var/lib/buildkit
      ignore_errors: yes

    - name: Forcefully remove /run/containerd and its contents
      command: rm -rf /run/containerd
      ignore_errors: yes

    - name: Forcefully remove /var/lib/containerd-stargz-grpc and its contents
      command: rm -rf /var/lib/containerd-stargz-grpc
      ignore_errors: yes

    - name: Forcefully remove /opt/nri and its contents
      command: rm -rf /opt/nri
      ignore_errors: yes

    - name: Forcefully remove /etc/nri and its contents
      command: rm -rf /etc/nri
      ignore_errors: yes

    - name: Remove /etc/containerd/
      command: rm -rf /etc/containerd
      ignore_errors: yes
