- name: Copy docker compose to target server
  copy:
    src: "../repo/docker-compose/{{ arch }}/{{ version }}/docker-compose-linux-{{ pkg_map[arch] }}"
    dest: "/tmp/docker-compose-linux-{{ pkg_map[arch] }}"

- name: Set execute permission for docker-compose
  file:
    path: "/tmp/docker-compose-linux-{{ pkg_map[arch] }}"
    mode: "0755"

- name: Ensure .docker/cli-plugins directory exists in the root directory
  file:
    path: "/root/.docker/cli-plugins"
    state: directory
    mode: '0755'

- name: Rename and move docker-compose to /usr/local/bin
  command: mv /tmp/docker-compose-linux-{{ pkg_map[arch] }} /root/.docker/cli-plugins/docker-compose
  args:
    removes: "/tmp/docker-compose-linux-{{ pkg_map[arch] }}"

