apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.31.0
controlPlaneEndpoint: "ubuntu:6443"
apiServer:
  extraArgs:
    advertise-address: "192.168.2.4"
networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "172.20.0.0/16"
criSocket: "unix:///var/run/containerd/containerd.sock"
