version: "3.9"
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: gitlab-runner
    volumes:
      - ./etc/config.toml:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
