---
- name: Ensure /usr/local/bin directory exists
  file:
    path: /usr/local/bin
    state: directory
    mode: '0755'

- name: Copy CRI tarball to target server
  copy:
    src: "../roles/kubernetes/release/x86_64/cri/crictl-v1.31.0-linux-amd64.tar.gz"
    dest: "/tmp"

- name: Ensure /opt/cni/bin directory exists
  file:
    path: /opt/cni/bin
    state: directory
    mode: '0755'

- name: Extract crictl-v1.31.0-linux-amd64.tar.gz to /opt/cni/bin
  ansible.builtin.unarchive:
    src: "/tmp/crictl-v1.31.0-linux-amd64.tar.gz"
    dest: "/opt/cni/bin"
    remote_src: yes

- name: Copy CNI tarball to target server
  copy:
    src: "../roles/kubernetes/release/x86_64/cni/cni-plugins-linux-amd64-v1.5.1.tgz"
    dest: "/tmp"

- name: Extract cni-plugins-linux-amd64-v1.5.1.tgz to /usr/local/bin
  ansible.builtin.unarchive:
    src: "/tmp/cni-plugins-linux-amd64-v1.5.1.tgz"
    dest: "/usr/local/bin"
    remote_src: yes

- name: Copy binary kubeadm to /usr/local/bin
  copy:
    src: "../roles/kubernetes/release/x86_64/main/kubeadm"
    dest: "/usr/local/bin/kubeadm"
    mode: '0755'

- name: Copy binary kubectl to /usr/local/bin
  copy:
    src: "../roles/kubernetes/release/x86_64/main/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: '0755'

- name: Copy binary kubelet to /usr/local/bin
  copy:
    src: "../roles/kubernetes/release/x86_64/main/kubelet"
    dest: "/usr/local/bin/kubelet"
    mode: '0755'

- name: Ensure /usr/lib/systemd/system directory exists
  file:
    path: /usr/lib/systemd/system
    state: directory
    mode: '0755'

- name: Copy kubelet.service to /usr/lib/systemd/system
  copy:
    src: "../roles/kubernetes/release/x86_64/conf/kubelet.service"
    dest: "/usr/lib/systemd/system/kubelet.service"
    mode: '0644'

- name: Ensure /usr/lib/systemd/system/kubelet.service.d directory exists
  file:
    path: /usr/lib/systemd/system/kubelet.service.d
    state: directory
    mode: '0755'

- name: Copy 10-kubeadm.conf to /usr/lib/systemd/system/kubelet.service.d
  copy:
    src: "../roles/kubernetes/release/x86_64/conf/10-kubeadm.conf"
    dest: "/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf"
    mode: '0644'

- name: Enable and start kubelet service
  command: systemctl enable --now kubelet

- name: Remove temporary CRI tarball
  file:
    path: /tmp/crictl-v1.31.0-linux-amd64.tar.gz
    state: absent

- name: Remove temporary CNI tarball
  file:
    path: /tmp/cni-plugins-linux-amd64-v1.5.1.tgz
    state: absent