---
# Add CRI
- name: Copy CRI tarball to target server
  copy:
    src: "../roles/kubernetes/release/x86_64/cri/{{ cri_tarball }}"
    dest: "{{ tmp_path }}"

- name: Ensure /usr/local/bin directory exists
  file:
    path: "{{ kube_bin_path }}"
    state: directory
    mode: "0755"

- name: Extract CRI tarball to /usr/local/bin
  ansible.builtin.unarchive:
    src: "{{ tmp_path }}/{{ cri_tarball }}"
    dest: "{{ kube_bin_path }}"
    remote_src: yes

- name: Copy CRI configuration to /etc
  copy:
    src: "../roles/kubernetes/release/x86_64/cri/{{ cri_yaml }}"
    dest: "/etc/crictl.yaml"
    mode: "0644"

# Add CNI
- name: Copy CNI tarball to target server
  copy:
    src: "../roles/kubernetes/release/x86_64/cni/{{ cni_tarball }}"
    dest: "{{ tmp_path }}"

- name: Ensure /opt/cni/bin directory exists
  file:
    path: "/opt/cni/bin"
    state: directory
    mode: "0755"

- name: Extract CNI tarball to /opt/cni/bin
  ansible.builtin.unarchive:
    src: "{{ tmp_path }}/{{ cni_tarball }}"
    dest: "/opt/cni/bin"
    remote_src: yes

# Remove temporary files
- name: Remove temporary files
  file:
    path: "{{ tmp_path }}/{{ item }}"
    state: absent
  loop:
    - "{{ cri_tarball }}"
    - "{{ cni_tarball }}"

# Add main binaries
- name: Copy kubeadm binary to /usr/local/bin
  copy:
    src: "../roles/kubernetes/release/x86_64/main/{{ kubeadm_bin }}"
    dest: "{{ kube_bin_path }}/{{ kubeadm_bin }}"
    mode: "0755"

# - name: Copy kubectl binary to /usr/local/bin
#   copy:
#     src: "../roles/kubernetes/release/x86_64/main/{{ kubectl_bin }}"
#     dest: "{{ kube_bin_path }}/{{ kubectl_bin }}"
#     mode: "0755"

- name: Copy kubelet binary to /usr/local/bin
  copy:
    src: "../roles/kubernetes/release/x86_64/main/{{ kubelet_bin }}"
    dest: "{{ kube_bin_path }}/{{ kubelet_bin }}"
    mode: "0755"

# Add kubelet config
- name: Ensure /usr/lib/systemd/system directory exists
  file:
    path: "{{ kube_service_path }}"
    state: directory
    mode: "0755"

- name: Copy kubelet.service to /usr/lib/systemd/system
  copy:
    src: "../roles/kubernetes/release/x86_64/conf/{{ kubelet_service_file }}"
    dest: "{{ kube_service_path }}/{{ kubelet_service_file }}"
    mode: "0644"

- name: Ensure /usr/lib/systemd/system/kubelet.service.d directory exists
  file:
    path: "{{ kube_service_d_path }}"
    state: directory
    mode: "0755"

- name: Copy 10-kubeadm.conf to /usr/lib/systemd/system/kubelet.service.d
  copy:
    src: "../roles/kubernetes/release/x86_64/conf/{{ kubelet_conf_file }}"
    dest: "{{ kube_service_d_path }}/{{ kubelet_conf_file }}"
    mode: "0644"

# - name: Enable and start kubelet service
#   command: systemctl enable --now kubelet
