version: "3"
services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx-gateway
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./var/log/nginx:/var/log/nginx
      - ./usr/share/nginx/html:/usr/share/nginx/html
      - ./etc/ssl:/etc/ssl
