---
- name: Debug multiple variables
  debug:
    msg:
      - "conntrack_deb: {{ conntrack_deb }}"
      - "conntrack_rpm: {{ conntrack_rpm }}"
      - "libnetfilter_cthelper_rpm: {{ libnetfilter_cthelper_rpm }}"
      - "libnetfilter_cttimeout_rpm: {{ libnetfilter_cttimeout_rpm }}"
      - "libnetfilter_queue_rpm: {{ libnetfilter_queue_rpm }}"

- name: Check if the system uses dpkg
  command: dpkg --version
  register: dpkg_check
  ignore_errors: yes
  failed_when: false

- name: Check if the system uses rpm
  command: rpm --version
  register: rpm_check
  ignore_errors: yes
  failed_when: false

- name: Set system package manager fact
  set_fact:
    package_manager: "{{ 'dpkg' if dpkg_check.rc == 0 else 'rpm' if rpm_check.rc == 0 else 'unknown' }}"

- name: Print system package manager
  debug:
    msg: "The system uses {{ package_manager }} as its package manager."

# dpkg
- name: Install conntrack if dpkg is available
  when: dpkg_check.rc == 0 and package_manager == "dpkg"
  block:
    - name: Check if conntrack is already installed
      ansible.builtin.command: dpkg -s conntrack
      register: conntrack_check
      ignore_errors: true

    - name: Copy conntrack to target server
      copy:
        src: "../repo/conntrack/{{ arch }}/{{ version }}/{{ conntrack_deb }}"
        dest: "/tmp/{{ conntrack_deb }}"
      when: conntrack_check.rc != 0

    - name: Install conntrack package
      ansible.builtin.apt:
        deb: /tmp/{{ conntrack_deb }}
      when: conntrack_check.rc != 0

    - name: Clean up installation file
      file:
        path: "/tmp/{{ conntrack_deb }}"
        state: absent
      when: conntrack_check.rc != 0

# rpm
- name: Install conntrack if rpm is available
  when: rpm_check.rc == 0 and package_manager == "rpm"
  block:
    - name: Copy conntrack-tools RPM to target server
      copy:
        src: "../repo/conntrack/{{ arch }}/{{ version }}/{{ conntrack_rpm }}"
        dest: "/tmp/{{ conntrack_rpm }}"
      when: rpm_check.rc == 0

    - name: Copy libnetfilter_cthelper RPM to target server
      copy:
        src: "../repo/conntrack/{{ arch }}/{{ version }}/{{ libnetfilter_cthelper_rpm }}"
        dest: "/tmp/{{ libnetfilter_cthelper_rpm }}"
      when: rpm_check.rc == 0

    - name: Copy libnetfilter_cttimeout RPM to target server
      copy:
        src: "../repo/conntrack/{{ arch }}/{{ version }}/{{ libnetfilter_cttimeout_rpm }}"
        dest: "/tmp/{{ libnetfilter_cttimeout_rpm }}"
      when: rpm_check.rc == 0

    - name: Copy libnetfilter_queue RPM to target server
      copy:
        src: "../repo/conntrack/{{ arch }}/{{ version }}/{{ libnetfilter_queue_rpm }}"
        dest: "/tmp/{{ libnetfilter_queue_rpm }}"
      when: rpm_check.rc == 0

    - name: Install libnetfilter_cthelper RPM
      yum:
        name: /tmp/{{ libnetfilter_cthelper_rpm }}
        state: present

    - name: Install libnetfilter_cttimeout RPM
      yum:
        name: /tmp/{{ libnetfilter_cttimeout_rpm }}
        state: present

    - name: Install libnetfilter_queue RPM
      yum:
        name: /tmp/{{ libnetfilter_queue_rpm }}
        state: present

    - name: Install conntrack-tools RPM
      yum:
        name: /tmp/{{ conntrack_rpm }}
        state: present

    - name: Clean up installation files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/{{ conntrack_rpm }}"
        - "/tmp/{{ libnetfilter_cthelper_rpm }}"
        - "/tmp/{{ libnetfilter_cttimeout_rpm }}"
        - "/tmp/{{ libnetfilter_queue_rpm }}"
