---
- name: Check if the system uses dpkg
  command: dpkg --version
  register: dpkg_check
  ignore_errors: yes
  failed_when: false

- name: Check if the system uses rpm
  command: rpm --version
  register: rpm_check
  ignore_errors: yes
  failed_when: false

- name: Set system package manager fact
  set_fact:
    package_manager: "{{ 'dpkg' if dpkg_check.rc == 0 else 'rpm' if rpm_check.rc == 0 else 'unknown' }}"

- name: Print system package manager
  debug:
    msg: "The system uses {{ package_manager }} as its package manager."

# dpkg
- name: Install conntrack if dpkg is available
  when: dpkg_check.rc == 0
  block:
    - name: Check if conntrack is already installed
      ansible.builtin.command: dpkg -s conntrack
      register: conntrack_check
      ignore_errors: true

    - name: Copy conntrack to target server
      copy:
        src: "../roles/conntrack/release/x86_64/1.4.7/conntrack_1%3a1.4.7-1+b2_amd64.deb"
        dest: "/tmp/conntrack_1%3a1.4.7-1+b2_amd64.deb"
      when: conntrack_check.rc != 0

    - name: Install conntrack package
      ansible.builtin.apt:
        deb: /tmp/conntrack_1%3a1.4.7-1+b2_amd64.deb
      when: conntrack_check.rc != 0

    - name: Clean up installation file
      file:
        path: "/tmp/conntrack_1%3a1.4.7-1+b2_amd64.deb"
        state: absent
      when: conntrack_check.rc != 0

# rpm
- name: Install conntrack if rpm is available
  when: rpm_check.rc == 0
  block:
    - name: Copy conntrack-tools RPM to target server
      copy:
        src: "../roles/conntrack/release/x86_64/1.4.7/conntrack-tools-1.4.7-2.el9.x86_64.rpm"
        dest: "/tmp/conntrack-tools-1.4.7-2.el9.x86_64.rpm"
      when: rpm_check.rc == 0

    - name: Copy libnetfilter_cthelper RPM to target server
      copy:
        src: "../roles/conntrack/release/x86_64/1.4.7/libnetfilter_cthelper-1.0.0-22.el9.x86_64.rpm"
        dest: "/tmp/libnetfilter_cthelper-1.0.0-22.el9.x86_64.rpm"
      when: rpm_check.rc == 0

    - name: Copy libnetfilter_cttimeout RPM to target server
      copy:
        src: "../roles/conntrack/release/x86_64/1.4.7/libnetfilter_cttimeout-1.0.0-19.el9.x86_64.rpm"
        dest: "/tmp/libnetfilter_cttimeout-1.0.0-19.el9.x86_64.rpm"
      when: rpm_check.rc == 0

    - name: Copy libnetfilter_queue RPM to target server
      copy:
        src: "../roles/conntrack/release/x86_64/1.4.7/libnetfilter_queue-1.0.5-1.el9.x86_64.rpm"
        dest: "/tmp/libnetfilter_queue-1.0.5-1.el9.x86_64.rpm"
      when: rpm_check.rc == 0

    - name: Install libnetfilter_cthelper RPM
      yum:
        name: /tmp/libnetfilter_cthelper-1.0.0-22.el9.x86_64.rpm
        state: present

    - name: Install libnetfilter_cttimeout RPM
      yum:
        name: /tmp/libnetfilter_cttimeout-1.0.0-19.el9.x86_64.rpm
        state: present

    - name: Install libnetfilter_queue RPM
      yum:
        name: /tmp/libnetfilter_queue-1.0.5-1.el9.x86_64.rpm
        state: present

    - name: Install conntrack-tools RPM
      yum:
        name: /tmp/conntrack-tools-1.4.7-2.el9.x86_64.rpm
        state: present

    - name: Clean up installation files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/conntrack-tools-1.4.7-2.el9.x86_64.rpm"
        - "/tmp/libnetfilter_cthelper-1.0.0-22.el9.x86_64.rpm"
        - "/tmp/libnetfilter_cttimeout-1.0.0-19.el9.x86_64.rpm"
        - "/tmp/libnetfilter_queue-1.0.5-1.el9.x86_64.rpm"
