---
- name: Copy nerdctl tarball from Ansible control node to target server
  copy:
    src: "../repo/nerdctl/{{ arch }}/{{ version }}/{{ pkg }}"
    dest: "/tmp/{{ pkg }}"

- name: Extract nerdctl tarball to /usr/local
  command: >
    tar Cxzvvf /usr/local /tmp/{{ pkg }}
  args:
    chdir: /tmp

- name: Clean up temporary files
  file:
    path: "/tmp/{{ pkg }}"
    state: absent

# - name: Copy nerdctl tarball
#   copy:
#     src: "../roles/nerdctl/config/certs.d/"
#     dest: "/etc/containerd/"
#     owner: root
#     group: root
#     mode: '0755'
#     recursive: yes

- name: Synchronize nerdctl certs directory
  synchronize:
    src: "../roles/nerdctl/config/certs.d/containerd"
    dest: "/etc/containerd/"
    mode: "push"

- name: Ensure /etc/cni/net.d exists
  file:
    path: "/etc/cni/net.d"
    state: directory
    mode: '0755'

- name: Copy containerd cni config
  copy:
    src: "../roles/nerdctl/config/cni/10-containerd-net.conflist"
    dest: "/etc/cni/net.d/"

- name: Enable and start containerd service
  systemd:
    name: containerd
    state: started
    enabled: yes

# - name: Enable and start buildkit service
#   systemd:
#     name: buildkit
#     state: started
#     enabled: yes

- name: Enable and start stargz-snapshotter service
  systemd:
    name: stargz-snapshotter
    state: started
    enabled: yes
