---
- name: Copy nerdctl tarball from Ansible control node to target server
  copy:
    src: "../repo/nerdctl/{{ arch }}/{{ version }}/{{ pkg }}"
    dest: "/tmp/{{ pkg }}"

- name: Extract nerdctl tarball to /usr/local
  command: >
    tar Cxzvvf /usr/local /tmp/{{ pkg }}
  args:
    chdir: /tmp

- name: Clean up temporary files
  file:
    path: "/tmp/{{ pkg }}"
    state: absent

- name: Copy nerdctl tarball from Ansible control node to target server
  copy:
    src: "../roles/nerdctl/config/config.toml"
    dest: "/etc/containerd/"

- name: Enable and start containerd service
  systemd:
    name: containerd
    state: started
    enabled: yes

# - name: Enable and start buildkit service
#   systemd:
#     name: buildkit
#     state: started
#     enabled: yes

- name: Enable and start stargz-snapshotter service
  systemd:
    name: stargz-snapshotter
    state: started
    enabled: yes
