- name: Copy buildx to target server
  copy:
    src: "../roles/docker-buildx/release/buildx-{{ version }}.{{ os }}-{{ arch }}"
    dest: "/tmp/buildx-{{ version }}.{{ os }}-{{ arch }}"

- name: Set execute permission for buildx
  file:
    path: "/tmp/buildx-{{ version }}.{{ os }}-{{ arch }}"
    mode: "0755"

- name: Rename and move buildx to /usr/local/bin
  command: mv /tmp/buildx-{{ version }}.{{ os }}-{{ arch }} /usr/local/bin/docker-buildx

- name: Clean up temporary file
  file:
    path: "/tmp/buildx-{{ version }}.{{ os }}-{{ arch }}"
    state: absent
