- name: Copy buildx to target server
  copy:
    src: "../repo/docker-buildx/{{ arch }}/{{ version }}/buildx-{{ version }}.linux-{{ pkg_map[arch] }}"
    dest: "/tmp/buildx-{{ version }}.linux-{{ pkg_map[arch] }}"

- name: Set execute permission for buildx
  file:
    path: "/tmp/buildx-{{ version }}.linux-{{ pkg_map[arch] }}"
    mode: "0755"

- name: Ensure .docker/cli-plugins directory exists in the root directory
  file:
    path: "/root/.docker/cli-plugins"
    state: directory
    mode: '0755'

- name: Rename and move buildx to .docker/cli-plugins/docker-buildx
  command: mv /tmp/buildx-{{ version }}.linux-{{ pkg_map[arch] }} /root/.docker/cli-plugins/docker-buildx
  args:
    removes: "/tmp/buildx-{{ version }}.linux-{{ pkg_map[arch] }}"
