---
# Add CRI
- name: Copy CRI tarball to target server
  copy:
    src: "../repo/CRI/{{ arch }}/{{ version }}/{{ pkg }}"
    dest: "/tmp"

- name: Ensure /usr/local/bin directory exists
  file:
    path: "/usr/local/bin"
    state: directory
    mode: "0755"

- name: Extract CRI tarball to /usr/local/bin
  ansible.builtin.unarchive:
    src: "/tmp/{{ pkg }}"
    dest: "/usr/local/bin"
    remote_src: yes

- name: Copy CRI configuration to /etc
  copy:
    src: "../roles/CRI/conf/crictl.yaml"
    dest: "/etc/crictl.yaml"
    mode: "0644"

# Remove temporary files
- name: Remove temporary files
  file:
    path: "/tmp/{{ item }}"
    state: absent
  loop:
    - "{{ pkg }}"
