# /etc/containerd/config.toml
files_by_version:
  "v1.7.6":
    - bin/nerdctl
    - bin/containerd-fuse-overlayfs-grpc
    - bin/tini
    - bin/bypass4netnsd
    - bin/ctd-decoder
    - bin/ipfs
    - bin/bypass4netns
    - bin/ctr
    - bin/containerd-stargz-grpc
    - bin/containerd
    - bin/ctr-remote
    - bin/buildg
    - bin/rootlesskit
    - bin/runc
    - bin/containerd-rootless-setuptool.sh
    - bin/fuse-overlayfs
    - bin/containerd-rootless.sh
    - bin/containerd-shim-runc-v2
    - bin/ctr-enc
    - bin/buildctl
    - bin/slirp4netns
    - bin/buildkitd
    - bin/rootlessctl
    - libexec/.DS_Store
    - libexec/cni/bandwidth
    - libexec/cni/dummy
    - libexec/cni/LICENSE
    - libexec/cni/ptp
    - libexec/cni/host-local
    - libexec/cni/bridge
    - libexec/cni/ipvlan
    - libexec/cni/tap
    - libexec/cni/firewall
    - libexec/cni/README.md
    - libexec/cni/vlan
    - libexec/cni/host-device
    - libexec/cni/macvlan
    - libexec/cni/sbr
    - libexec/cni/static
    - libexec/cni/loopback
    - libexec/cni/dhcp
    - libexec/cni/tuning
    - libexec/cni/vrf
    - libexec/cni/portmap
    - lib/systemd/system/containerd.service
    - lib/systemd/system/stargz-snapshotter.service
    - lib/systemd/system/buildkit.service
    - share/doc/nerdctl/docs/cosign.md
    - share/doc/nerdctl/docs/command-reference.md
    - share/doc/nerdctl/docs/ipfs.md
    - share/doc/nerdctl/docs/cni.md
    - share/doc/nerdctl/docs/builder-debug.md
    - share/doc/nerdctl/docs/cvmfs.md
    - share/doc/nerdctl/docs/faq.md
    - share/doc/nerdctl/docs/gpu.md
    - share/doc/nerdctl/docs/ocicrypt.md
    - share/doc/nerdctl/docs/multi-platform.md
    - share/doc/nerdctl/docs/dir.md
    - share/doc/nerdctl/docs/experimental.md
    - share/doc/nerdctl/docs/config.md
    - share/doc/nerdctl/docs/overlaybd.md
    - share/doc/nerdctl/docs/compose.md
    - share/doc/nerdctl/docs/stargz.md
    - share/doc/nerdctl/docs/build.md
    - share/doc/nerdctl/docs/rootless.md
    - share/doc/nerdctl/docs/notation.md
    - share/doc/nerdctl/docs/soci.md
    - share/doc/nerdctl/docs/registry.md
    - share/doc/nerdctl/docs/freebsd.md
    - share/doc/nerdctl/docs/nydus.md
    - share/doc/nerdctl/README.md
    - share/doc/nerdctl-full/README.md
    - share/doc/nerdctl-full/SHA256SUMS

  "v2.0.0":
    - bin/nerdctl
    - bin/containerd-fuse-overlayfs-grpc
    - bin/tini
    - bin/bypass4netnsd
    - bin/ctd-decoder
    - bin/bypass4netns
    - bin/ctr
    - bin/containerd-stargz-grpc
    - bin/containerd
    - bin/ctr-remote
    - bin/buildg
    - bin/rootlesskit
    - bin/runc
    - bin/containerd-rootless-setuptool.sh
    - bin/fuse-overlayfs
    - bin/containerd-rootless.sh
    - bin/containerd-shim-runc-v2
    - bin/ctr-enc
    - bin/buildctl
    - bin/slirp4netns
    - bin/buildkitd
    - bin/rootlessctl
    - libexec/.DS_Store
    - libexec/cni/bandwidth
    - libexec/cni/dummy
    - libexec/cni/LICENSE
    - libexec/cni/ptp
    - libexec/cni/host-local
    - libexec/cni/bridge
    - libexec/cni/ipvlan
    - libexec/cni/tap
    - libexec/cni/firewall
    - libexec/cni/README.md
    - libexec/cni/vlan
    - libexec/cni/host-device
    - libexec/cni/macvlan
    - libexec/cni/sbr
    - libexec/cni/static
    - libexec/cni/loopback
    - libexec/cni/dhcp
    - libexec/cni/tuning
    - libexec/cni/vrf
    - libexec/cni/portmap
    - lib/.DS_Store
    - lib/systemd/.DS_Store
    - lib/systemd/system/containerd.service
    - lib/systemd/system/stargz-snapshotter.service
    - lib/systemd/system/buildkit.service
    - share/.DS_Store
    - share/doc/nerdctl/docs/cosign.md
    - share/doc/nerdctl/docs/command-reference.md
    - share/doc/nerdctl/docs/ipfs.md
    - share/doc/nerdctl/docs/cni.md
    - share/doc/nerdctl/docs/builder-debug.md
    - share/doc/nerdctl/docs/images/nerdctl-white.svg
    - share/doc/nerdctl/docs/images/nerdctl.svg
    - share/doc/nerdctl/docs/images/rootlessKit-network-design.png
    - share/doc/nerdctl/docs/cvmfs.md
    - share/doc/nerdctl/docs/faq.md
    - share/doc/nerdctl/docs/gpu.md
    - share/doc/nerdctl/docs/ocicrypt.md
    - share/doc/nerdctl/docs/multi-platform.md
    - share/doc/nerdctl/docs/dir.md
    - share/doc/nerdctl/docs/experimental.md
    - share/doc/nerdctl/docs/config.md
    - share/doc/nerdctl/docs/testing/README.md
    - share/doc/nerdctl/docs/testing/tools.md
    - share/doc/nerdctl/docs/overlaybd.md
    - share/doc/nerdctl/docs/compose.md
    - share/doc/nerdctl/docs/stargz.md
    - share/doc/nerdctl/docs/build.md
    - share/doc/nerdctl/docs/dev/store.md
    - share/doc/nerdctl/docs/rootless.md
    - share/doc/nerdctl/docs/notation.md
    - share/doc/nerdctl/docs/soci.md
    - share/doc/nerdctl/docs/registry.md
    - share/doc/nerdctl/docs/freebsd.md
    - share/doc/nerdctl/docs/nydus.md
    - share/doc/nerdctl/README.md
    - share/doc/.DS_Store
    - share/doc/nerdctl-full/README.md
    - share/doc/nerdctl-full/SHA256SUMS
