version: '3.9'

volumes:
  pgadmin:

services:
  db:
    image: postgres
    restart: always
    working_dir: '/root'
    environment:
      POSTGRES_USER: username
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: passwd@1234
    ports:
      - 5432:5432
    volumes:
      - './db_data:/var/lib/postgresql/data'
      - './script/enter-database.sh:/root/enter-database.sh'
      - './script/dbbackup.sql:/root/dbbackup.sql'
  # adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080

  # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  pgweb:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "18090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "1421130266@qq.com"
      PGADMIN_DEFAULT_PASSWORD: "666666"
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db