---
- name: 启用 kubelet 并加入 Kubernetes 集群
  hosts: all
  become: yes
  vars:
    control_plane: "node:6443"
    kubeadm_token: "xxxx.xxxxxxxxxxxx"
    discovery_token_ca_cert_hash: "sha256:xxxx"
    is_control_plane: "--control-plane"
  tasks:
    - name: 启用并启动 kubelet 服务
      systemd:
        name: kubelet
        state: started
        enabled: yes

    - name: 加入 Kubernetes 集群
      command: >
        kubeadm join {{ control_plane }} --token {{ kubeadm_token }}
        --discovery-token-ca-cert-hash {{ discovery_token_ca_cert_hash }} 
        {{ is_control_plane }}
      register: join_output
      ignore_errors: yes

    - name: 显示加入集群的输出
      debug:
        var: join_output.stdout