---
- name: Enable kubelet and join Kubernetes cluster
  hosts: all
  become: yes
  vars:
    control_plane: "node:6443"
    kubeadm_token: "xxxx.xxxxxxxxxxxx"
    discovery_token_ca_cert_hash: "sha256:xxxx"
    is_control_plane: "--control-plane"
  tasks:
    - name: Enable and start kubelet service
      systemd:
        name: kubelet
        state: started
        enabled: yes

    - name: Join Kubernetes cluster
      command: >
        kubeadm join {{ control_plane }} --token {{ kubeadm_token }}
        --discovery-token-ca-cert-hash {{ discovery_token_ca_cert_hash }} 
        {{ is_control_plane }}
      register: join_output
      ignore_errors: yes

    - name: Display join cluster output
      debug:
        var: join_output.stdout
