---
- name: Remove Kubernetes binaries and configuration
  hosts: all
  become: yes
  tasks:
    - name: Remove Kubernetes binaries
      file:
        path: "/usr/local/bin/{{ item }}"
        state: absent
      loop:
        - kubeadm
        - kubectl
        - kubelet

    - name: Remove CNI plugins
      file:
        path: "/usr/local/bin/{{ item }}"
        state: absent
      loop:
        - cni-plugins-linux-amd64-v1.5.1

    - name: Remove CRI tools
      file:
        path: "/opt/cni/bin/{{ item }}"
        state: absent
      loop:
        - crictl

    - name: Remove kubelet systemd service file
      file:
        path: "/usr/lib/systemd/system/kubelet.service"
        state: absent

    - name: Remove kubelet systemd drop-in directory
      file:
        path: "/usr/lib/systemd/system/kubelet.service.d"
        state: absent
        recurse: yes

    - name: Remove kubelet systemd drop-in configuration file
      file:
        path: "/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf"
        state: absent

    - name: Remove temporary files
      file:
        path: "/tmp/{{ item }}"
        state: absent
      loop:
        - crictl-v1.31.0-linux-amd64.tar.gz
        - cni-plugins-linux-amd64-v1.5.1.tgz

    - name: Disable and stop kubelet service
      command: systemctl stop kubelet
      ignore_errors: yes

    - name: Disable kubelet service
      command: systemctl disable kubelet
      ignore_errors: yes

    - name: Reload systemd daemon
      command: systemctl daemon-reload