# containerd/tasks/main.yml
---
- name: Install wget
  package:
    name: wget
    state: present

- name: Download nerdctl tarball
  include_tasks: download.yml

- name: Extract nerdctl tarball
  include_tasks: extract.yml