---
- name: Ensure /etc/systemd/system/user@.service.d directory exists
  file:
    path: /etc/systemd/system/user@.service.d
    state: directory
    mode: '0755'

- name: Create or update /etc/systemd/system/user@.service.d/delegate.conf
  copy:
    dest: /etc/systemd/system/user@.service.d/delegate.conf
    content: |
      [Service]
      Delegate=cpu cpuset io memory pids
    mode: '0644'

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Prompt for reboot
  debug:
    msg: "Please log out and log back in, or reboot the system for changes to take effect."
