---
- name: Copy nerdctl tarball from Ansible control node to target server
  copy:
    src: "{{ nerdctl_base_dir }}/{{ nerdctl_tarball }}"
    dest: "{{ nerdctl_dest_path }}"

- name: Ensure /usr/local/nerdctl directory exists
  file:
    path: /usr/local/nerdctl
    state: directory
    mode: "0755"

- name: Extract nerdctl tarball to /usr/local/nerdctl
  command: >
    tar -xzvf {{ nerdctl_dest_path }} -C /usr/local/nerdctl
  args:
    chdir: /tmp

- name: Add /usr/local/nerdctl/bin to PATH
  lineinfile:
    path: /etc/profile
    line: "export PATH=$PATH:/usr/local/nerdctl/bin"
    state: present

- name: Source /etc/profile to update PATH
  shell: source /etc/profile
  args:
    executable: /bin/bash

- name: Clean up temporary files
  file:
    path: "{{ nerdctl_dest_path }}"
    state: absent
