---
- name: Copy nerdctl tarball from Ansible control node to target server
  copy:
    src: "{{ nerdctl_base_dir }}/{{ nerdctl_tarball }}"
    dest: "{{ nerdctl_dest_path }}"

- name: Extract nerdctl tarball to /usr/local
  command: >
    tar Cxzvvf /usr/local {{ nerdctl_dest_path }}
  args:
    chdir: /tmp

- name: Clean up temporary files
  file:
    path: "{{ nerdctl_dest_path }}"
    state: absent

- name: Copy nerdctl tarball from Ansible control node to target server
  copy:
    src: "../roles/containerd/release/config.toml"
    dest: "/etc/containerd/"

- name: Enable and start containerd service
  systemd:
    name: containerd
    state: started
    enabled: yes

- name: Enable and start buildkit service
  systemd:
    name: buildkit
    state: started
    enabled: yes

- name: Enable and start stargz-snapshotter service
  systemd:
    name: stargz-snapshotter
    state: started
    enabled: yes
